### ISSUE TITLE
About GKD

### ISSUE THREAD

**Issue by jaehoon00** [WisonZ/GKD#4]
Hi and first, thank you for sharing such a fascinating work.
I am trying to experiment GKD based on EKD repository from TFace, following your recommendation.
EKD appears to be using (balanced, general) batch concepts and BalancedBatchSampler.
Do I need those for GKD as well? Or, just using DistributedSampler is fine?

**Comment by WisonZ** [comment]
General sampler (random sampling) is okay.

**Comment by jaehoon00** [comment]
Okay, thank you.
