### ISSUE TITLE
Question about training settings

### ISSUE THREAD

**Issue by Leun9** [WisonZ/GKD#6]
We note that training settings is different between this repo and paper. One is {margin=0.4, CosLr with nesterov, Vanilla GKD}, the other is {margin=0.5, StepLr, Adaptive GKD}. Which one could be used to reproduce the GKD result on Tab. 5?

**Comment by WisonZ** [comment]
The performance (CosFace(m=0.4) & CosLr) is marginally better than that of original setting (ArcFace(m=0.5) & StepLr).

**Comment by WisonZ** [comment]
You can directly use the code I have uploaded before.

**Comment by Leun9** [comment]
> You can directly use the code I have uploaded before.

So, should I directly use the vanilla GKD rather than adaptive GKD?

**Comment by WisonZ** [comment]
yes
